### ISSUE TITLE
Unable to attach plugin r2ghidra-dec using r2pm

### ISSUE THREAD

**Issue by notsuspiciousindividual** [radareorg/r2ghidra-dec#100]
### Unable to attach plugin r2ghidra-dec using r2pm

Tried using r2pm -i r2ghidra-dec, installation seems to fail at a certain point

Environment when downloading
git commit ac5355fb
Ubuntu 19.10 TLS
gcc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008
radare2 4.5.0-git 24503 @ linux-x86-64 git.4.4.0-86-gac5355fb3
r2pm 4.5.0-git

Error:
![Capture](https://user-images.githubusercontent.com/33929871/80303788-fae7a600-87e4-11ea-9664-8f4b0d7a527a.PNG)

I've tried to refer back to error [#76](https://github.com/radareorg/r2ghidra-dec/issues/76) but it does not solve the issue. Do update me if there are additional information that I should provide. Thank you in advance.

**Comment by notsuspiciousindividual** [comment]
Would like to edit the previous post with a better screenshot to ease with debugging. 
![image](https://user-images.githubusercontent.com/33929871/80304083-8877c580-87e6-11ea-94d5-a5af2e1dd752.png)

**Comment by thestr4ng3r** [comment]
Thanks for reporting, it's now in sync with r2 master again.
