### ISSUE TITLE
Custom prefix path of rizin's include

### ISSUE THREAD

**Issue by dmknght** [radareorg/r2ghidra-dec#225]
I'm compiling the project as standalone Debian package. For now the `prefix` of rizin is at `/usr/` instead of `/usr/local/` and `rz-ghidra` only use `/usr/local/` as default prefix. I would like to know is there any cmake flag that can change this value? From the doc, i can only set the include source of rz-cutter using `-DCUTTER_SOURCE_DIR=/usr/include/librz-cutter`.

**Comment by thestr4ng3r** [comment]
Does `-DCMAKE_INSTALL_PREFIX=/usr` do what you want?
See https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html and maybe https://cmake.org/cmake/help/latest/envvar/DESTDIR.html on top.

**Comment by dmknght** [comment]
> Does `-DCMAKE_INSTALL_PREFIX=/usr` do what you want?
> See https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html and maybe https://cmake.org/cmake/help/latest/envvar/DESTDIR.html on top.

I am using this flag and it doesn't change the include of `rizin` headers. Sorry my bad i didn't give flags i'm using. Those are
`-DBUILD_CUTTER_PLUGIN=ON -DCUTTER_SOURCE_DIR=/usr/include/librz-cutter -DCMAKE_INSTALL_PREFIX=/usr/`
P/s: As far as i understand, the `CMAKE_INSTALL_PREFIX` sets the destinaion of project will be installed at so i don't think this flag is what i need.

**Comment by karliss** [comment]
You shouldn't be using `-DCUTTER_SOURCE_DIR=/usr/include/librz-cutter`  if you have a properly compiled and installed cutter it should included all the required files for plugin compilation and the cmake library description. As for the way rizin headers are searched, on Linux that should be handled by pkg-config. pkg-config should use /usr by default. Additional directories can be added using PKG_CONFIG_PATH environement variable or -DCMAKE_PREFIX_PATH.

**Comment by dmknght** [comment]
> You shouldn't be using `-DCUTTER_SOURCE_DIR=/usr/include/librz-cutter` if you have a properly compiled and installed cutter it should included all the required files for plugin compilation and the cmake library description. As for the way rizin headers are searched, on Linux that should be handled by pkg-config. pkg-config should use /usr by default. Additional directories can be added using PKG_CONFIG_PATH environement variable or -DCMAKE_PREFIX_PATH.

Thank you. The flag `-DCMAKE_PREFIX_PATH` fixed the problem. The path of Cutter's header was customized and when i removed it, the cmake showed error can't find cutter source. I finally can build with flags `-DBUILD_CUTTER_PLUGIN=ON -DCUTTER_SOURCE_DIR=/usr/include/librz-cutter -DCMAKE_INSTALL_PREFIX=/usr/ -DCMAKE_PREFIX_PATH=/usr`.
With rizin 0.1.1 and rz-ghidra 0.2.0 i'm having compile error 
```
/tmp/rizin-ghidra-plugin/src/core_ghidra.cpp:695:15: error: invalid conversion from ‘bool (*)(RzCore*)’ {aka ‘bool (*)(rz_core_t*)’} to ‘RzCmdCb’ {aka ‘int (*)(void*, const char*)’} [-fpermissive]
  695 |  /*.init = */ rz_ghidra_init,
      |               ^~~~~~~~~~~~~~
      |               |
      |               bool (*)(RzCore*) {aka bool (*)(rz_core_t*)}
/tmp/rizin-ghidra-plugin/src/core_ghidra.cpp:696:15: error: invalid conversion from ‘bool (*)(RzCore*)’ {aka ‘bool (*)(rz_core_t*)’} to ‘RzCmdCb’ {aka ‘int (*)(void*, const char*)’} [-fpermissive]
  696 |  /*.fini = */ rz_ghidra_fini
      |               ^~~~~~~~~~~~~~
      |               |
      |               bool (*)(RzCore*) {aka bool (*)(rz_core_t*)}
```
but this is not problem of this topic so i'm closing it. I'm running the rz-ghidra compilation from `rz-pm` to see if it can compile.

**Comment by thestr4ng3r** [comment]
Ok I thought you were looking for a flag for where to install rz-ghidra to. For search, `CMAKE_PREFIX_PATH` is indeed correct.
rz-ghidra 0.2.0 and rizin 0.1.1 are not compatible so that is expected.

**Comment by dmknght** [comment]
> Ok I thought you were looking for a flag for where to install rz-ghidra to. For search, `CMAKE_PREFIX_PATH` is indeed correct.
> rz-ghidra 0.2.0 and rizin 0.1.1 are not compatible so that is expected.

Thank you i didn't release rizin 0.2.0 released when i commented :D I updated and rebuilt cutter and my deb package rizin, rizin-cutter and rizin-ghira works perfectly.
