### ISSUE TITLE
Missing header rz_type.h when install from rz-pm

### ISSUE THREAD

**Issue by dmknght** [radareorg/r2ghidra-dec#226]
I installed rizin 2.0 into system using debian packaging. After testing install rz-ghidra by command
`rz-pm install rz-ghidra` i'm having this error:
```
/home/dmknght/.local/share/rizin/rz-pm/git/rz-ghidra/src/RizinTypeFactory.cpp:7:10: fatal error: rz_type.h: No such file or directory
    7 | #include <rz_type.h>
      |          ^~~~~~~~~~~
compilation terminated.
```
After checking files, i found the actual name is `rz_types.h`. `rz-ghidra` is missing `s` in the name.
The problem likely is on the latest git version only but not in release `0.2.0`.

**Comment by dmknght** [comment]
Some files are using `rz_type.h`
```
cmake/FindRizin.cmake:                        NAMES rz_core.h rz_bin.h rz_util.h rz_type.h
src/RizinTypeFactory.cpp:#include <rz_type.h>
```

**Comment by dmknght** [comment]
Source code from release 0.2.0
```
src/RizinScope.h:#include <rz_types.h>
```

**Comment by dmknght** [comment]
I changed the lame of rz_type and i saw some error is showing. Is the changes were made for rizin 0.2.1?

**Comment by thestr4ng3r** [comment]
Yes, rz-pm only works with rz-ghidra dev + rizin dev.

**Comment by dmknght** [comment]
> Yes, rz-pm only works with rz-ghidra dev + rizin dev.

Thank you good to know. So i think this issue can be closed now because it is wrong version that made by me only?
