### ISSUE TITLE
Wrong path and name for library in pkg-config and on disk

### ISSUE THREAD

**Issue by davendu** [radareorg/r2ghidra-dec#234]
In #232, new libraries are exported. However, it does not work since:

1. In `rz_ghidra.pc.in:12-13`, `@RIZIN_INSTALL_PLUGDIR@` should not be appened after `libs`
2. Files generated in `/usr/local/lib` are not correctly named. It should be named like `libcore_ghidra.dylib`, instad of `core_ghidra.dylib`.

**Comment by XVilka** [comment]
2. Is intended - it's linked directly by the name `-l:core_ghidra${suffix}`

**Comment by davendu** [comment]
> 2 Is intended - it's linked directly by the name `-l:core_ghidra${suffix}`

I see, but the string thing is it does not work...need to manually modify `pkg-config` and rename the file.

**Comment by ret2libc** [comment]
@XVilka why was the .pc file needed? Do we use RzGhidra as a library anywhere? Asking because the core_ghidra.so library is anyway in a non-standard path usually (the rizin plugins dir) so it won't be picked up automatically by the loader.

**Comment by XVilka** [comment]
@ret2libc we did use it as a library. I am not sure about a better/right way to solve this.

**Comment by ret2libc** [comment]
Where?

**Comment by XVilka** [comment]
@ret2libc it's classified.

**Comment by ret2libc** [comment]
Then I don't know how to help on this.
