### ISSUE TITLE
some files can not decompile ''memory corruption'' ''invalid next size''

### ISSUE THREAD

**Issue by callmebigfeng** [radareorg/r2ghidra-dec#235]
When i decompile，some files cannot be decompiled due to ''memory corruption'' ,''invalid next size'' . I put example for each of these two errors in the attachmentone .
[memory corruption.zip](https://github.com/rizinorg/rz-ghidra/files/6584618/memory.corruption.zip)
[invalid next size.zip](https://github.com/rizinorg/rz-ghidra/files/6584620/invalid.next.size.zip)

**Comment by Rubonnek** [comment]
[overlapping_input_varnodes.zip](https://github.com/rizinorg/rz-ghidra/files/6587180/overlapping_input_varnodes.zip) at function 0x000025c0

**Comment by thestr4ng3r** [comment]
Minimal example:
[heritage-overflow.raw.gz](https://github.com/rizinorg/rz-ghidra/files/7186388/heritage-overflow.raw.gz)
Just load as a raw binary with arm/32/le, analyze a function at offset 0, `pdg` and watch it fail.

**Comment by thestr4ng3r** [comment]
It's a bug in Ghidra, reported to them here: https://github.com/NationalSecurityAgency/ghidra/issues/3429
