### ISSUE TITLE
How to install on android

### ISSUE THREAD

**Issue by stupidestmodder** [radareorg/r2ghidra-dec#241]
trying to install this in termux outputs a error
![Screenshot_20210808-181928_Termux](https://user-images.githubusercontent.com/44854972/128646128-3bdb8f08-2d35-4d60-94e2-a5a1178ee15f.jpg)
any wait to fix this?

**Comment by Young-Lord** [comment]
me too, but on WSL(Ubuntu 20.04)

**Comment by thestr4ng3r** [comment]
rz-pm is indeed too broken to be useful in its current state. Please build manually from source using the instructions in the readme.
