### ISSUE TITLE
Regression Bug: fail to build due to `not` token from `librz/rz_il/rzil_opcodes.h`

### ISSUE THREAD

**Issue by chinggg** [radareorg/r2ghidra-dec#258]
https://github.com/rizinorg/rizin/pull/1663 defines `RzILOpNot * not ;` in https://github.com/rizinorg/rizin/blob/69b509a15756d518999568aa3a3e240b3143e053/librz/include/rz_il/rzil_opcodes.h#L412
But `not` is an *alternative token* in C++, so CMake complains about it:
```
/usr/local/include/librz/rz_il/rzil_opcodes.h:412:20: error: expected unqualified-id before ‘not’ token
  412 |         RzILOpNot *not;
```
Can this be fixed by modifying CMake files? Or it requries change of code in upstream?

**Comment by thestr4ng3r** [comment]
Fixed by https://github.com/rizinorg/rizin/pull/1820
