### ISSUE TITLE
Installing in WSL-ubuntu fails (root rights is needed)

### ISSUE THREAD

**Issue by ogre2007** [radareorg/r2ghidra-dec#266]
Idk if it should be so, but I can't install plugin w/o root rights. If it should, maybe some README.md changes is needed.
`rz-pm -i rz-ghidra
Install the project...
-- Install configuration: ""
-- Installing: /home/user/.local/share/rizin/plugins/core_ghidra.so
-- Set runtime path of "/home/user/.local/share/rizin/plugins/core_ghidra.so" to ""
-- Installing: /home/user/.local/share/rizin/plugins/asm_ghidra.so
-- Set runtime path of "/home/user/.local/share/rizin/plugins/asm_ghidra.so" to "$ORIGIN"
-- Installing: /home/user/.local/share/rizin/plugins/analysis_ghidra.so
-- Set runtime path of "/home/user/.local/share/rizin/plugins/analysis_ghidra.so" to "$ORIGIN"
-- Installing: /usr/local/include/rz_ghidra.h
CMake Error at cmake_install.cmake:142 (file):
  file INSTALL cannot copy file
  "/home/user/.local/share/rizin/rz-pm/git/rz-ghidra/src/rz_ghidra.h" to
  "/usr/local/include/rz_ghidra.h": Permission denied.`

**Comment by thestr4ng3r** [comment]
rz-pm is indeed too broken to be useful in its current state. Please build manually from source using the instructions in the readme.
