### ISSUE TITLE
Problem with building with Cmake in Windows 10, Visual Studio 2019

### ISSUE THREAD

**Issue by fred26** [radareorg/r2ghidra-dec#268]
I am trying to build on windows. CMAKE is telling me paths are missing:

> Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19042.
searching for file: r_core
Library set to Radare2_LIBRARY_core-NOTFOUND
searching for file: r_config
Library set to Radare2_LIBRARY_config-NOTFOUND
searching for file: r_cons
Library set to Radare2_LIBRARY_cons-NOTFOUND
searching for file: r_io
Library set to Radare2_LIBRARY_io-NOTFOUND
searching for file: r_util
Library set to Radare2_LIBRARY_util-NOTFOUND
searching for file: r_flag
Library set to Radare2_LIBRARY_flag-NOTFOUND
searching for file: r_asm
Library set to Radare2_LIBRARY_asm-NOTFOUND
searching for file: r_debug
Library set to Radare2_LIBRARY_debug-NOTFOUND
searching for file: r_hash
Library set to Radare2_LIBRARY_hash-NOTFOUND
searching for file: r_bin
Library set to Radare2_LIBRARY_bin-NOTFOUND
searching for file: r_lang
Library set to Radare2_LIBRARY_lang-NOTFOUND
searching for file: r_io
Library set to Radare2_LIBRARY_io-NOTFOUND
searching for file: r_anal
Library set to Radare2_LIBRARY_anal-NOTFOUND
searching for file: r_parse
Library set to Radare2_LIBRARY_parse-NOTFOUND
searching for file: r_bp
Library set to Radare2_LIBRARY_bp-NOTFOUND
searching for file: r_egg
Library set to Radare2_LIBRARY_egg-NOTFOUND
searching for file: r_reg
Library set to Radare2_LIBRARY_reg-NOTFOUND
searching for file: r_search
Library set to Radare2_LIBRARY_search-NOTFOUND
searching for file: r_syscall
Library set to Radare2_LIBRARY_syscall-NOTFOUND
searching for file: r_socket
Library set to Radare2_LIBRARY_socket-NOTFOUND
searching for file: r_fs
Library set to Radare2_LIBRARY_fs-NOTFOUND
searching for file: r_magic
Library set to Radare2_LIBRARY_magic-NOTFOUND
searching for file: r_crypto
Library set to Radare2_LIBRARY_crypto-NOTFOUND
CMake Error at C:/Program Files/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Radare2 (missing: Radare2_LIBRARIES Radare2_INCLUDE_DIRS)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindRadare2.cmake:119 (find_package_handle_standard_args)
  CMakeLists.txt:85 (find_package)

> Configuring incomplete, errors occurred!

> See also "D:/Users/feder/Files/Code/Development/r2ghidra-master/build/CMakeFiles/CMakeOutput.log".

I have installed Radare2 binaries and created manually Radare2_LIBRARIES and  Radare2_INCLUDE_DIRS, pointing them to radare2-5.4.2-w64\lib and radare2-5.4.2-w64\include respectively.

I appreciate any hint on how to proceed with succesful compilation.
Thanks

**Comment by trufae** [comment]
I think you want to report that to https://github.com/radareorg/r2ghidra

**Comment by fred26** [comment]
Thanks
