### ISSUE TITLE
build crashing while doing the "make"

### ISSUE THREAD

**Issue by V33RU** [radareorg/r2ghidra-dec#27]
R2Architecture.cpp:191:13: error: ‘RAnalFunction {aka struct r_anal_function_t}’ has no member named ‘is_noreturn’
   if (func->is_noreturn)
CMakeFiles/core_ghidra.dir/build.make:75: recipe for target 'CMakeFiles/core_ghidra.dir/src/R2Architecture.cpp.o' failed
make[2]: *** [CMakeFiles/core_ghidra.dir/src/R2Architecture.cpp.o] Error 1
CMakeFiles/Makefile2:83: recipe for target 'CMakeFiles/core_ghidra.dir/all' failed
make[1]: *** [CMakeFiles/core_ghidra.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by pelijah** [comment]
Update r2

**Comment by V33RU** [comment]
r2pm -i r2ghidra-dec


this works fine thnak you

**Comment by ITAYC0HEN** [comment]
Good :) let us know if you are experiencing any other issue
