### ISSUE TITLE
stand-alone usage ?

### ISSUE THREAD

**Issue by rofl0r** [radareorg/r2ghidra-dec#270]
hi, i think this project could be very useful if it offered a way to use it outside the rizin/cutter framework as a command line tool (in order to cut down on dependencies, and to make it usable with all sorts of tools).
maybe by just piping some disassembled code into it or by pointing it to an .s file ?

**Comment by thestr4ng3r** [comment]
You can do all sorts of things using rizin's command line options, e.g. `rizin -AQc 'pdg @ main' <some file>`, which makes rz-ghidra as a standalone tool obsolete. Anything else not related to rizin is out of scope of this project.
