### ISSUE TITLE
Rizin cmake config not found

### ISSUE THREAD

**Issue by FalcoGer** [radareorg/r2ghidra-dec#274]
I compiled Cutter from source using a clone from the cutter github repository in the stable branch and following https://cutter.re/docs/building.html

I built with python bindings and graphviz and ksyntaxhighlight using ninja build.

Building this way apparently didn't come with ghidra support. So i tried to install it with `rz-pm -i rz-ghidra`. It didn't work. I got the following output

```text
Already up to date.
error: pathspec 'rz-0.3.2' did not match any file(s) known to git
Already up to date.
Install Done For rz-ghidra
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:8 (find_package):
  By not providing "FindRizin.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Rizin", but
  CMake did not find one.

  Could not find a package configuration file provided by "Rizin" with any of
  the following names:

    RizinConfig.cmake
    rizin-config.cmake

  Add the installation prefix of "Rizin" to CMAKE_PREFIX_PATH or set
  "Rizin_DIR" to a directory containing one of the above files.  If "Rizin"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/paul/.local/share/rizin/rz-pm/git/rz-ghidra/build/CMakeFiles/CMakeOutput.log".
```

I have tried looking for those .cmake files in the cutter repository and rizin submodule but couldn't find them anywhere.

**Comment by FalcoGer** [comment]
I have compiled rizin on it's own and installed it and then compiled cutter without the bundled rizin. I get the same result. I used the stable branches for both.

**Comment by FalcoGer** [comment]
I found a workaround.
I went into the repository directory and checked out the stable branch of rz-ghidra. afterwards running `rz-pm -i rz-ghidra` worked fine. But it wanted root rights because it installed some stuff into /usr/local/include/
However it did not install the cutter plugin. I had to manually compile it again.
Right now rz-pm is useless to install ghidra.

**Comment by thestr4ng3r** [comment]
Removed rz-pm from the docs because it indeed is too broken to be useful.
