### ISSUE TITLE
rz-ghidra 3.0 can't build with rizin 0.3.x backend

### ISSUE THREAD

**Issue by dmknght** [radareorg/r2ghidra-dec#278]
cmake command uses by debian packaging `$cd obj-x86_64-linux-gnu && cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_RUNSTATEDIR=/run -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON "-GUnix Makefiles" -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_INSTALL_LIBDIR=lib/x86_64-linux-gnu -DBUILD_CUTTER_PLUGIN=ON -DCUTTER_SOURCE_DIR=/usr/include/librz-cutter -DCMAKE_INSTALL_PREFIX=/usr/ -DCMAKE_PREFIX_PATH=/usr ..`

# Error
```
-- Checking for one of the modules 'rz_core'
CMake Error at /usr/share/cmake-3.22/Modules/FindPkgConfig.cmake:890 (message):
  None of the required 'rz_core' found
Call Stack (most recent call first):
  cmake/FindRizin.cmake:92 (pkg_search_module)
  CMakeLists.txt:74 (find_package)


CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Rizin (missing: Rizin_TARGET Rizin_LIBRARIES
  Rizin_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindRizin.cmake:113 (find_package_handle_standard_args)
  CMakeLists.txt:74 (find_package)
```

![image](https://user-images.githubusercontent.com/29118926/154292515-9c63a9e8-cafb-4fb7-8cba-2b95c85c5cec.png)

Error logs
[rizin_builderr_CMakeOutput.log](https://github.com/rizinorg/rz-ghidra/files/8080950/rizin_builderr_CMakeOutput.log)
[rizin_builderr_rz-pm.log](https://github.com/rizinorg/rz-ghidra/files/8080955/rizin_builderr_rz-pm.log)

**Comment by dmknght** [comment]
Maybe this issue relates to [#234](https://github.com/rizinorg/rz-ghidra/issues/234)?

**Comment by dmknght** [comment]
Update: Maybe something is wrong with either `pkg-config` or `librizin-dev` because
1. rizin 0.2.x and ghidra worked just fine
2. On my machine, i reinstall `librizin-dev` and ghidra compiled succesfully. However, virtual build environment didn't work.

**Comment by ret2libc** [comment]
I think I will close this. I tested compilation of both main branches rizin/rz-ghidra on a clean debian-bullseye container and everything worked (no cutter, but it should not be the problem here). I also tested rizin v0.3.4 with rz-ghidra 0.3.0 and it worked. We are about to ship 0.4.0 anyway.

Let me know @dmknght if you still have troubles.

**Comment by dmknght** [comment]
> I think I will close this. I tested compilation of both main branches rizin/rz-ghidra on a clean debian-bullseye container and everything worked (no cutter, but it should not be the problem here). I also tested rizin v0.3.4 with rz-ghidra 0.3.0 and it worked. We are about to ship 0.4.0 anyway.
> 
> Let me know @dmknght if you still have troubles.

Hello! Thank you for your info. I'm testing under vm right now and i'll test again when next version releases
Update: Tested and confirmed everything is fine on my side.
