### ISSUE TITLE
ghidra submodule points to orphan commit leading to distro packaging issues

### ISSUE THREAD

**Issue by anthraxx** [radareorg/r2ghidra-dec#295]
Hi folks,

I'm an Arch Linux package maintainer maintaining rizin. While Upgrading to the latest version, I have discovered the following issue:

rz-ghidra has a submodule of ghidra (https://github.com/rizinorg/ghidra) which currently (and in the latest release) points to commit  https://github.com/rizinorg/ghidra/tree/d87905747fe38d2dcd7492ed2e83bbf438b156d3
This is an orphan commit that is neither referenced by a branch nor a tag and hence loose (as GitHub notifies via "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository").

The issue is, when building with distro packaging tools the sources are only pulled for none loose objects, hence facing issues with the submodule in rz-ghidra not being able to check out the ghidra submodule.

Would it be possible to always push a git tag in https://github.com/rizinorg/ghidra which will held the referenced commit of the submodule and therefor never make that referenced commit actually being an orphan object?

Thank you very much :cat:

**Comment by thestr4ng3r** [comment]
It is on master now and will be tagged as `rz-ghidra-legacy-13` when superseded.
Thanks for noticing.

**Comment by anthraxx** [comment]
Thanks for the speedy fix
