### ISSUE TITLE
Deb package to integrate rz-ghidra in Kali

### ISSUE THREAD

**Issue by danielefaugiana** [radareorg/r2ghidra-dec#314]
What about creating a .deb package for the plugin so we can request Kali to integrate it in the distro? Is there any reason why packages are not provided? [A package for Arch](https://archlinux.org/packages/community/x86_64/rz-ghidra/) exists in the community repo. Are you interested in maintaining here a deb package or do you prefer having it managed by someone else outside of this repo?

**Comment by thestr4ng3r** [comment]
We only provide the source. It is up to the distributions themselves to make specific packages. See for example parrot for a .deb: https://gitlab.com/parrotsec/packages/rizin-ghidra-plugin/-/tree/master/debian

**Comment by danielefaugiana** [comment]
That makes sense. Thanks for answering!
