### ISSUE TITLE
Cannot be found in r2pm in Linux

### ISSUE THREAD

**Issue by RomeuG** [radareorg/r2ghidra-dec#32]
Hey.

Tried to install on Linux using the command `r2pm -i r2ghidra-dec`, being this the output:
```
Cannot find r2ghidra-dec
```

This is my version of Radare2 on Linux:
```
radare2 3.8.0 0 @ linux-x86-64 git.3.8.0
commit: unknown build: 2019-09-03__21:20:08
```

R2pm outputs the same version number: `r2pm 3.8.0`.

Thanks.

**Comment by xarkes** [comment]
Hello, I think you need to update your r2pm repositories.
Try typing `r2pm update` and then try the command again.

**Comment by RomeuG** [comment]
You are completely right. I didn't know I had to run that command in the first place.
Thank you very much!
