### ISSUE TITLE
PIC (mcu) architecture support

### ISSUE THREAD

**Issue by karliss** [radareorg/r2ghidra-dec#355]
In theory both Ghidra and Rizin support it, but there is no mapping in https://github.com/rizinorg/rz-ghidra/blob/733ad009bd603a9ea03d386d2781acff7a150ee2/src/ArchMap.cpp .

Not sure how much additional arch specific code is required besides that. Might also have some adressing/memory region weirdness due to Harvard architecture (like many 8bit MCUs).

**Comment by XVilka** [comment]
@imbillow could you please add also the mapping for PIC and https://github.com/rizinorg/rz-ghidra/issues/341?
