### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by radare** [radareorg/r2ghidra-dec#45]
```
$ r2 -A rr
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for objc references
[x] Check for vtables
[x] Type matching analysis for all functions (aaft)
[x] Propagate noreturn information
[x] Use -AA or aaaa to perform additional experimental analysis.
[0x100000a80]> pdg
Segmentation fault: 11
$
```

[rr.zip](https://github.com/radareorg/r2ghidra-dec/files/3670319/rr.zip)

**Comment by thestr4ng3r** [comment]
works for me
![Screenshot 2019-09-30 at 13 02 39](https://user-images.githubusercontent.com/1460997/65873157-9c5b6600-e382-11e9-953d-7824e6ca3fae.png)

**Comment by jacobrosenthal** [comment]
Also getting a segfault
macosx 10.14.6 (18G103)

radare2 4.0.0-git 23058 @ darwin-x86-64 git.3.9.0-73-g5193b7284

commit: 5193b7284ec83fcb66ed8df44c808243f1ab0eab build: 2019-09-29__13:41:32

**Comment by radare** [comment]
nvm, i just rebuilt the plugin after r2 and worked, my fault
