### ISSUE TITLE
r2pm -i r2ghidra-dec doesn't work

### ISSUE THREAD

**Issue by n0u4n** [radareorg/r2ghidra-dec#51]
-- Checking for one of the modules 'r_core'
CMake Error at /usr/share/cmake-3.13/Modules/FindPkgConfig.cmake:679 (message):
  None of the required 'r_core' found
Call Stack (most recent call first):
  cmake/FindRadare2.cmake:80 (pkg_search_module)
  CMakeLists.txt:43 (find_package)

CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Radare2 (missing: Radare2_TARGET Radare2_LIBRARIES
  Radare2_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindRadare2.cmake:97 (find_package_handle_standard_args)
  CMakeLists.txt:43 (find_package)

-- Configuring incomplete, errors occurred!

Am I doing something wrong?

**Comment by thestr4ng3r** [comment]
How and where did you install radare2?

**Comment by n0u4n** [comment]
I have r2 default installed in my distro (Parrot). The version is 3.7.1. But I tried installing r2 4.0 from git in a debian vm and then r2pm -i r2ghidra-dec and it fails as well

**Comment by n0u4n** [comment]
I solved the issue. It was a missing dipendency in the parrot repo. it missed libzip-dev. now parrot-devs solved the problem. sorry it was not a r2ghidra-dec problem. thank you

**Comment by itsallmathematics** [comment]
I am having this exact issue as well but in Ubuntu 18.04. What are the current/proper versions of libradare?

**Comment by radare** [comment]
4.3 or 4.4
