### ISSUE TITLE
Ghidra Decompiler Error: No sleigh specification for x86:BE:32:default

### ISSUE THREAD

**Issue by Cyper77** [radareorg/r2ghidra-dec#62]
**Environment information**
* Operating System: windows 7sp1
* Cutter version: 1.10.0
* File format: pe
 * Arch: x86
 * Type: EXEC (Executable file)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by thestr4ng3r** [comment]
Closing because no response
