### ISSUE TITLE
Honor asm.flags.realname in the output

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/r2ghidra-dec#64]
Currently, r2ghidra will show flag names even when `asm.flags.realname` is enabled.

When this variable is enabled, Ghidra should show the flags' realname.
Thus, showing `VirtualAllocEx(0x1000);` instead of `sym.imp.kernel33.dll_VirtualAllocEx(0x1000);`.

It is expected that r2ghidra will honor the eval variable when enabled.

**Comment by radare** [comment]
Agree
