### ISSUE TITLE
Unknown calling convention for ARM v9 binaries?

### ISSUE THREAD

**Issue by romansavrulin** [radareorg/r2ghidra-dec#66]
**Environment information**
* Operating System: **OSX**
* Cutter version: 
* Obtained from:
  - [] Built from source
  - [ ] Downloaded from release
  - [x] Distribution repository
* File format: **ELF**

**Describe the bug**

I'm trying to analyze ARMv9 binary, compilled with `arm-linux-gnueabihf-gcc` and getting the following warnings in decompiler:

```
Unknown calling convention yet parameter storage is locked
[r2ghidra] Matching calling convention arm32 of function sym.imp.abort failed, args may be inaccurate.
```

I've tried different types of analysis and different types of architecture settings. The best result is achieved with automatic `aaa` preset

how can I provide Cutter with calling convention type or add support for ARM v9?

**Screenshots**

![image](https://user-images.githubusercontent.com/1313542/72264685-30002c00-362c-11ea-8f0c-8ac12b9ce0f2.png)

**Comment by ITAYC0HEN** [comment]
Thank you for letting us know!
I moved the issue to r2ghidra-dec repository since it's related to the plugin itself and not to Cutter.=

**Comment by romansavrulin** [comment]
@ITAYC0HEN Can you point me how can I add support for this binaries?

**Comment by thestr4ng3r** [comment]
I was looking for the place in the code (https://github.com/radareorg/r2ghidra-dec/blob/master/src/R2Architecture.cpp#L26) to show you how to fix it, but then accidentally fixed it myself :see_no_evil: 

r2's arm32 cc maps to __stdcall in sleigh so I added that. It can still happen that you see incorrect function args, especially for imported functions, but that is better tracked in #73.

**Comment by romansavrulin** [comment]
Nice! So how can I introduce this to my Cutter (Currently stable release)? Should I build from source or do you have some sort of nightly builds stream?

**Comment by thestr4ng3r** [comment]
The best way is to build all from source, but a new release is scheduled soon too. There are no nightlies provided unfortunately.

**Comment by ITAYC0HEN** [comment]
Unless you're on windows and then you can download the artifact from AppVeyor
