### ISSUE TITLE
Add note for runtime dependencies: requires g++/libstdc++.so.6

### ISSUE THREAD

**Issue by Nicceboy** [radareorg/r2ghidra-dec#67]
Hello.
I had a bit rare use case for r2ghidra decompiler. I was making multi-stage Docker image (alpine base) with radare2 and this plugin installed. The purpose of multi-staging was to minimize the size of the image -> drop all build dependencies and layers.

However, after copying build binaries from build image into runtime image, plugin just did not decompile binaries correctly into C - code; it just showed same assembly code than `pdf` command.

After many hours, I figured out that shared lib `g++/libstdc++.so.6` is required, which was not in
 runtime image. This is bit obvious afterwards...

Maybe this would be good to mention somewhere.

r2ghidra-dec commands did not rise any errors. Debug mode in in radare2 revealed the reason:
```
/ $ export R_DEBUG=true
/ $ r2 /bin/ls
Cannot open directory '/usr/local/lib/radare2/4.2.0-git'
Cannot open /home/appuser/.local/share/radare2/plugins/r2ghidra_sleigh
Loading /home/appuser/.local/share/radare2/plugins/core_ghidra.so
r_lib_dl_open: error: /home/appuser/.local/share/radare2/plugins/core_ghidra.so (Error loading shared library libstdc++.so.6: No such file or directory (needed by /home/appuser/.local/share/radare2/plugins/core_ghidra.so))
Cannot open library: '/home/appuser/.local/share/radare2/plugins/core_ghidra.so'
Cannot open directory '/usr/local/lib/radare2/4.2.0-git'
Cannot open directory '/usr/local/lib/radare2-extras/4.2.0-git'
Cannot open directory '/usr/local/lib/radare2-bindings/4.2.0-git'
```

Hopefully this helps someone else!

**Comment by thestr4ng3r** [comment]
r2ghidra itself does not directly depend on any particular c++ std lib, it eventually comes down to how you build it. It should work with libstdc++, libc++, whatever microsoft has, ...

If you don't have libstdc++ in your runtime image and you would run any C++ program in it, it would fail in the same way. I think the major complication here is that it's not directly obvious why r2 won't load the library without using R_DEBUG.

**Comment by radare** [comment]
You can statically link this lib to avoid deending on it at runtime

**Comment by Nicceboy** [comment]
Thank you for clarification. Have to figure out how to build it statically. For some reason I expected it was already built.

**Comment by thestr4ng3r** [comment]
I think for docker it might make more sense to install libstdc++ in the runtime image instead of linking statically, but that is up to you.

**Comment by Nicceboy** [comment]
Image is only used for running what it contains, so I'm just trying to minimize the size. g++ takes 170 MB as installed with dependencies.

**Comment by thestr4ng3r** [comment]
Normally libstdc++ should be its own package, which does not depend on the compiler but idk.

**Comment by Nicceboy** [comment]
> 
> 
> Normally libstdc++ should be its own package, which does not depend on the compiler but idk.

Indeed it was. Thank you! I think you can close  issue, as itself it serves something if someone encounters similar issues. Use case might be rare.

**Comment by thestr4ng3r** [comment]
Nice!
