### ISSUE TITLE
Ghidra decompiler error: No sleigh specification for 68000:BE:16:default

### ISSUE THREAD

**Issue by lab313ru** [radareorg/r2ghidra-dec#75]
This problem happens on decompiling any Sega Mega Drive rom (there is a loader for it).
Version info is:
Version 1.10.0
Using r2-4.1.1
Based on Qt 5.12.5 (MSVC 2017, 64 bit)

To decompile 68k functions 68000:BE:32:default must be used.

Binary: [tf3.zip](https://github.com/radareorg/r2ghidra-dec/files/4103236/tf3.zip)

**Comment by thestr4ng3r** [comment]
The mapping is fixed now. By the way, when automatic matching fails, you can always manually specify the id by doing `e r2ghidra.lang=68000:BE:32:default` for example.
