### ISSUE TITLE
build crashes

### ISSUE THREAD

**Issue by alex-curiou** [radareorg/r2ghidra-dec#76]
Build crashes during 'make' and during 'r2pm -i r2ghidra-dec' on fresh radare2 installation.
Last build-able commit is 01fc83a000230c834003cb551630f6466ff9fe51

OS:  **Ubuntu 18.04.3 LTS** (GNU/Linux 4.4.0-18362-Microsoft x86_64) - WSL
**gcc** (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

**radare2** 4.2.0-git 23697 @ linux-x86-64 git.4.1.1-29-gbac525d8e
commit: bac525d8e9bc8765b74e134c135a7c9e73e00c07 build: 2020-01-24__09:13:33

**r2pm** 4.2.0-git

/home/alex/.local/share/radare2/r2pm/git/r2ghidra-dec.git/src/R2Scope.cpp:436:23: error: ‘r_anal_get_function_at’ was not declared in this scope
  RAnalFunction *fcn = r_anal_get_function_at(core->anal, addr);
                       ^~~~~~~~~~~~~~~~~~~~~~
/home/alex/.local/share/radare2/r2pm/git/r2ghidra-dec.git/src/R2Scope.cpp:436:23: note: suggested alternative: ‘r_anal_get_fcn_at’
  RAnalFunction *fcn = r_anal_get_function_at(core->anal, addr);
                       ^~~~~~~~~~~~~~~~~~~~~~
                       r_anal_get_fcn_at

....

[r2ghidra-build-failure.txt](https://github.com/radareorg/r2ghidra-dec/files/4107148/r2ghidra-build-failure.txt)

**Comment by ITAYC0HEN** [comment]
It seems like your version of radare2 is not up to date. Recently, changes were added to radare2 that you should have for the latest r2ghidra-dec to work,
Please try to update your version of radare2 and let us know if it works :)

**Comment by alex-curiou** [comment]
Yes,
You are right, thank You

after 'git hard --reset' + 'git clean -fdx'
The install.sh script has updated radare2 to version 4.3.0-git 23697
And there is no issue for this version

**Comment by ITAYC0HEN** [comment]
Great!! Thank you for taking the time to report and open an issue :)
